name: iOS Debug Build & Release

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  PROJECT_NAME: fastlane078
  SCHEME_NAME: fastlane078
  IOS_WORKSPACE: ios/$PROJECT_NAME.xcworkspace

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install npm dependencies
        run: npm ci

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: |
          gem install cocoapods
          pod install --repo-update

      - name: Import Signing Certificate
        env:
          SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        run: |
          echo $SIGNING_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security list-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          sudo security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Install Provisioning Profile
        env:
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
        run: |
          echo $PROVISIONING_PROFILE | base64 -di > $PROJECT_NAME.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles/
          cp $PROJECT_NAME.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          /usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin < $PROJECT_NAME.mobileprovision > uuid.tmp
          PROVISION_UUID=$(cat uuid.tmp)
          mv ~/Library/MobileDevice/Provisioning\ Profiles/$PROJECT_NAME.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROVISION_UUID.mobileprovision

      - name: Setup Fastlane
        working-directory: ios
        run: |
          bundle install
          bundle exec fastlane --version

      - name: Build and Export IPA
        working-directory: ios
        env:
          FASTLANE_APP_IDENTIFIER: ${{ secrets.IOS_APP_ID }}
          FASTLANE_TEAM_ID: ${{ secrets.IOS_TEAM_ID }}
        run: |
          bundle exec fastlane build_debug

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: debug-build-${{ github.run_id }}
          name: Debug Build ${{ github.run_number }}
          files: ios/build/fastlane078.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
